config/routes.rb
Rails.application.routes.draw do
  # mainpage
  
  

  get "about", to: "about#index"
  get "tips", to: "tips#index"
  
  get "ai", to: "ai#index"

  get "aiplus", to: "aiplus#index"
  get "aiplus", to: "aiplus#generate_imageplus"
  post "aiplus", to: "aiplus#index"
  
  get "amazonbedrock", to: "amazonbedrock#index"
  get "create_image", to: "amazonbedrock#create_image"
  post "create_image", to: "amazonbedrock#create_image"


  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  #get "save_image", to: "save_images#new"
  get "save_image", to: "aiplus#index"
  post "save_image", to: "aiplus#save_image"

  get "edit_image_titles", to: "edit_image_titles#edit"
  

  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"

  get "dashboard", to: "dashboard#index"
  post "deleteimage", to: "dashboard#destroy"
  delete "deleteimage", to: "dashboard#destroy"

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  

  root to: "main#index"
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

 
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :require_user_logged_in!
    def index
        
   

        @images = Image.where(:user_id => session[:user_id]).all
        puts session[:user_id]
    end

    def destroy
        
        @image = Image.find(params[:id])
        @image.destroy
        flash[:notice] = "Image successfully deleted"
        redirect_to(:action => 'index')
    end
    
      
end

app/views/dashboard/index.html.erb
<h1>My Dashboard</h1>
<%= "Dashboard for: " + Current.user.username %>
<div>
<%= link_to "Edit Password", password_path, :class => "btn btn-outline-dark m-1" %>
</div>

<h2> My Saved Images </h2>

<center>
<table class="table table-sm">

  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= "\"#{image.title}\"" %></td>
        <td><%= image_tag("https://ai-images-promptlab.s3.amazonaws.com/"+"#{image.url}", class:"img-thumbnail rounded mx-auto d-block", :align=> "left",style:"width:200px;") %></td>
        <td><%= button_to "Edit", edit_image_titles_path(image),:class => "btn btn-outline-dark m-1" %></td>
        <td><%= button_to 'Delete', deleteimage_path(action: :delete, id: image.id),:class => "btn btn-outline-dark m-1",
  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></td>
         </tr>
    <% end %>
  </tbody>
</table>
</center>

<br>