config/routes.rb
Rails.application.routes.draw do
  # mainpage
  
  

  get "about", to: "about#index"
  get "tips", to: "tips#index"
  
  get "ai", to: "ai#index"

  get "aiplus", to: "aiplus#index"
  get "aiplus", to: "aiplus#generate_imageplus"
  post "aiplus", to: "aiplus#index"
  
  get "amazonbedrock", to: "amazonbedrock#index"
  get "create_image", to: "amazonbedrock#create_image"
  post "create_image", to: "amazonbedrock#create_image"


  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  #get "save_image", to: "save_images#new"
  get "save_image", to: "aiplus#index"
  post "save_image", to: "aiplus#save_image"

  get "edit_image_titles", to: "edit_image_titles#edit"
  

  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"

  get "dashboard", to: "dashboard#index"
  post "deleteimage", to: "dashboard#destroy"
  delete "deleteimage", to: "dashboard#destroy"

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  

  root to: "main#index"
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

 
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new

    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            #send email
            PasswordMailer.with(user: @user).reset.deliver_later


            redirect_to root_path, notice: "If a user with that email was found, an email verification code will be sent shortly."
      
        else
            redirect_to root_path, notice: "If a user with that email was found, an email verification code will be sent shortly."
      
        end
    end

        def edit
            @user = User.find_signed!(params[:token], purpose: "password_reset")
        rescue ActiveSupport::MessageVerifier::InvalidSignature
            redirect_to password_reset_path, alert: "Your token has expired."
        end

        def update
            @user = User.find_signed!(params[:token], purpose: "password_reset")
            if @user.update(password_params)
                redirect_to log_in_path, notice: "Your password was reset."
            else
                render :edit

            end
        end

        private
        def password_params
            params.require(:user).permit(:password,:password_confirmation)
        end

end

app/views/password_resets/edit.html.erb
<h1>Reset your password </h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
        <%= form.object.errors.full_messages.each do |message|%>
            <div><%= message %></div>
        <% end %>
        </div>
    <%end%>

   <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control",placeholder: "som3th!ngG00d" %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation,class: "form-control", placeholder: "som3th!ngG00d"%>
    </div>

    <div class="mb-3">
    
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>

<% end%>

app/views/password_resets/new.html.erb
<h1> Forgot your password?</h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">

        <%= form.label :email %>
        <%= form.text_field :email , class: "form-control", placeholder:"yim@code.org"%>

    </div>

    <div class="mb-3">
    
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>

<% end%>