config/routes.rb
Rails.application.routes.draw do
  # mainpage
  
  

  get "about", to: "about#index"
  get "tips", to: "tips#index"
  
  get "ai", to: "ai#index"

  get "aiplus", to: "aiplus#index"
  get "aiplus", to: "aiplus#generate_imageplus"
  post "aiplus", to: "aiplus#index"
  
  get "amazonbedrock", to: "amazonbedrock#index"
  get "create_image", to: "amazonbedrock#create_image"
  post "create_image", to: "amazonbedrock#create_image"


  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  #get "save_image", to: "save_images#new"
  get "save_image", to: "aiplus#index"
  post "save_image", to: "aiplus#save_image"

  get "edit_image_titles", to: "edit_image_titles#edit"
  

  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"

  get "dashboard", to: "dashboard#index"
  post "deleteimage", to: "dashboard#destroy"
  delete "deleteimage", to: "dashboard#destroy"

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  

  root to: "main#index"
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

 
end

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
    <div class="alert alert-success mt-4" role="alert">
    <%= flash[:notice] %>
    </div>
<% end %>


<% if flash[:alert]%>
    <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container footer relative-bottom">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">&copy; 2024 Yim Register</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
    <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
          
        </li>

      
       
    </ul>
  </footer>
</div>

<div class="b-example-divider"></div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Yim Learns Ruby", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
          
        </li>

        <!--<li class="nav-item">
          <%= link_to "AI Image Generation", ai_path, class: "nav-link" %>
          
        </li>-->

        <li class="nav-item">
          <%= link_to "Open AI Image Gen", aiplus_path, class: "nav-link" %>
          
        </li>
        <li class="nav-item">
          <%= link_to "Amazon Titan Image Gen", amazonbedrock_path, class: "nav-link" %>
          
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <%if Current.user %>
        <li class="nav-item">
        <%= link_to  Current.user.username, dashboard_path, class:"nav-link m-1"%>
        </li>
        <li class="nav-item">
        <%= button_to "Logout", logout_path, method: :delete,class: "btn btn-outline-dark m-1" %>
        </li>
        <% else %>
          <li class="nav-item">
          <%= link_to "Login", log_in_path, class: "btn btn-outline-dark m-1"%>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "btn btn-outline-dark m-1" %>
          </li>
        <%end%>
      </ul>
     
    </div>
  </div>
</nav>

app/views/shared/_prompt.html.erb
<div class="alert alert-info" role="alert">
  <h4 class="alert-heading">Nice job!</h4>
  <p>Your prompt:  <%= content_tag(:b, "' " + "#{@prompt}" + "'")%></p>
  <hr>
  <%= link_to "💡 Tips on making an even better prompt.", tips_path, :class => "nav-link" %>
</div>