config/routes.rb
Rails.application.routes.draw do
  # mainpage
  
  

  get "about", to: "about#index"
  get "tips", to: "tips#index"
  
  get "ai", to: "ai#index"

  get "aiplus", to: "aiplus#index"
  get "aiplus", to: "aiplus#generate_imageplus"
  post "aiplus", to: "aiplus#index"
  
  get "amazonbedrock", to: "amazonbedrock#index"
  get "create_image", to: "amazonbedrock#create_image"
  post "create_image", to: "amazonbedrock#create_image"


  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  #get "save_image", to: "save_images#new"
  get "save_image", to: "aiplus#index"
  post "save_image", to: "aiplus#save_image"

  get "edit_image_titles", to: "edit_image_titles#edit"
  

  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"

  get "dashboard", to: "dashboard#index"
  post "deleteimage", to: "dashboard#destroy"
  delete "deleteimage", to: "dashboard#destroy"

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  

  root to: "main#index"
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

 
end

app/controllers/aiplus_controller.rb
class AiplusController < ApplicationController
  require 'open-uri'
    def index
      # renders views/aiplus/index.html.erb

      # if they haven't input anything yet
      # TODO: better error checking here
      if params[:noun].blank?
        #fill in the result image with the placeholder image
        @result = 'yourimage.png'
        
      # otherwise, process their prompt
      else
        prompt = params[:noun] +' ' +params[:descriptor]+ ' ' + params[:verb]
      
        # TODO: this needs to be initialized somewhere else, not every time 
        client = OpenAI::Client.new(
        access_token: Rails.application.credentials.dig(:openai, :api_key_secret),
        log_errors: true # Highly recommended in development, so you can see what errors OpenAI is returning. Not recommended in production because it could leak private data to your logs.
        )
      
        # error catching block
        begin
          # try to generate the image from the prompt given
          @image_data = client.images.generate(parameters: { prompt:  prompt, size: "256x256" })
          
          # however, the API may return an error, sometimes for content moderation
        rescue Faraday::Error => e
          # TODO: make sure this helper works
          handle_error()

        else #if no error
          #puts @image_data.dig("data", 0, "url")
  
          # Process @image_data and display the image in the view
          if @image_data && @image_data["data"].is_a?(Array) && @image_data["data"].any?
            image_url = @image_data["data"].first()["url"]
            @prompt = prompt
            @result = image_url
            
            render :index, status: 422
          end
        end
      
    
    end
  end


def new
    @image = Image.new
end


def save_image
  if params[:url] == "yourimage.png" 
    
    @result ='yourimage.png'
    flash.now[:alert] = "Image not saved, please generate an AI image."
    render :index 
  else
    @image = Image.new(title: params[:title],url: params[:url],user_id: session[:user_id]) 
    require 'open-uri'
    require 'uri'
    @image.save!
    File.open('app/assets/images/'+ "#{@image.id}" +'.png', 'wb') do |fo|
        fo.write URI.open(params[:url]).read
        
      end 
  
      @image.url ="#{@image.id}"+".png"

      #absolutely initialize somewhere else, not every time!!!
      credentials = Aws::Credentials.new(
        Rails.application.credentials.dig(:aws, :access_key_id), Rails.application.credentials.dig(:aws, :secret_access_key)
        )
    s3 = Aws::S3::Resource.new(region:'us-east-1',credentials:credentials)
    obj = s3.bucket("ai-images-promptlab").object(@image.url) # make sure your filename has an extension (.jpg for example)

    File.open(open('app/assets/images/'+ "#{@image.id}" +'.png'), 'rb') do |file|
      obj.put(body: file)
    end
    
    #workaround temp image saved to local, pushed to bucket, then deleted
    if @image.save
        File.delete('app/assets/images/'+ "#{@image.id}" +'.png')
        #session[:user_id] = @user.id
        redirect_to dashboard_path, notice: "Saved your image: \"" + "#{params[:title]}" +"\""
    
      
      end
  
  end
  
  

  
end

def image_params
  params.require(:image).permit(:id, :title, :url, :user_id )
end


def handle_error
  flash.now[:alert] =  "Oops! Your prompt \"" + "#{prompt}" + "\" includes a restricted word. Try again."
          # TODO: log the prompts that go against rules in an Errors model
          
          params[:noun]= nil # why do I do this? to reset the image on reload? bad logic
          @prompt = nil # reset the prompt
          @result = 'yourimage.png' # reset the image
          render :index, status: 422 #give status so turbo works, re-render index to start over but with flash alert

end






end
    

app/views/aiplus/index.html.erb
<div class="container ">
  <h1 class="text-center mb-2 ">Open AI Image Generation</h1>
  <center><%= image_tag("lilbot.gif", :style => "width:6%;") %></center>

  
  <!-- Centered form -->
  <div class="d-flex justify-content-center align-items-center display:flex">

    <div class="col-md-4 m-3 align-self-baseline">
      <div class="rounded p-4 bg-light">
        <!-- Form for input prompt
        <form id="generate-form">
          <div class="form-group">
            <label for="noun" class="mb-2">Noun:</label>
            <input type="text" class="form-control mb-3" id="noun" name="noun" placeholder="E.g., 'A robot'">
            <label for="descriptor" class="mb-2">Descriptor:</label>
            <input type="text" class="form-control mb-3" id="descriptor" name="descriptor" placeholder="E.g., 'with glasses'">
            <label for="noun" class="mb-2">Verb:</label>
            <input type="text" class="form-control mb-3" id="verb" name="verb" placeholder="E.g., 'learning to code'">
            
          </div>-->
          
          <!--<div class="d-grid gap-2">-->
            <!-- Generate Button -->
            <!--<button id="generate_imageplus" type="submit" class="btn btn-primary btn-block">Generate Image</button>-->
            <!-- Display area for generated image -->
            <!--<div class="mt-4 text-center" id="generated-img">-->
              <!-- Image will be displayed here -->

             
            

           <!-- </div>
          </div>
        </form>-->

    <%= form_with url: aiplus_path, data:{"data-turbo-track": "reload"} do |form| %>
    <div class="mb-3">

        <%= form.label :noun %>
        <%= form.text_field :noun , class: "form-control", placeholder:"E.g. a robot"%>

    </div>

    <div class="mb-3">

        <%= form.label :descriptor %>
        <%= form.text_field :descriptor , class: "form-control", placeholder:"E.g. with glasses"%>

    </div>

    <div class="mb-3">

        <%= form.label :verb %>
        <%= form.text_field :verb , class: "form-control", placeholder:"E.g. learning to code"%>

    </div>

    <div class="mb-3">
    
    <%= form.submit "Generate Image", id: "generate_imageplus",class: "btn btn-primary", onclick:"document.body.style.cursor='wait'; return true;"%>
    </div>
    
</div>

<% end%>


     
    </div>
    <div class="m-3">
    <%= render partial: "shared/prompt" if params[:noun].present?%>
    <%= image_tag("#{@result}", width:"256px;") %><br>

    <div>

    <%= form_with model: @image, data: { turbo: false }, url: save_image_path, method: :post do |form| %>

    <div class="mb-3">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control",placeholder: "My AI Image" %>
       
        <%= form.hidden_field :url, :value => "#{@result}" %>

    </div>

    <div class="mb-3">
        
        <%= form.submit "Save Image", class: "btn btn-primary"%>
    </div>

<% end %>
    </div>


   
    </div>
  </div>
</div>